# Generated by Django 5.1 on 2024-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
