# Generated by Django 5.1 on 2024-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchy", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="current_session",
        ),
        migrations.RemoveField(
            model_name="user",
            name="room",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
