version: '3.8'

services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    build:
      context: backend
      dockerfile: Dockerfile
      target: api-prod
    env_file:
      - .env.prod
    depends_on:
      - watchy-redis
      - watchy-db
    volumes:
      - ./backend/static:/code/backend/static
    environment:
      - REDIS_PASSWORD=passwo4509b14a24a8rd
    restart: always
    networks:
      - watchy_network

  watchy-redis:
    image: redis:latest
    container_name: watchy-redis
    restart: always
    command: >
      sh -c "exec redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./redis.prod.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=passwo4509b14a24a8rd
    networks:
      - watchy_network

  watchy-db:
    image: postgres:latest
    container_name: watchy-db
    env_file:
      - .env.prod
    restart: always
    networks:
      - watchy_network

  watchy-frontend:
    container_name: watchy-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - watchy_network

  watchy-nginx:
    container_name: watchy-nginx
    image: nginx:1.25
    restart: always
    ports:
      - "82:80"
    depends_on:
      - watchy-api
      - watchy-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/static
    networks:
      - watchy_network

networks:
  watchy_network:

volumes:
  redis-data:
