version: '3.8'

services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    build:
      context: .
      dockerfile: Dockerfile
      target: api-test
    env_file:
      - .env.dev
    depends_on:
      - watchy-redis
      - watchy-db
    volumes:
      - ./clocks:/app/clocks
    networks:
      - watchy_network

  watchy-redis:
    image: redis:latest
    container_name: watchy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=password
    networks:
      - watchy_network

  watchy-db:
    image: postgres:latest
    container_name: watchy-db
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    restart: always
    networks:
      - watchy_network

  watchy-nginx:
    image: nginx:latest
    container_name: watchy-nginx
    restart: always
    ports:
      - "82:80"
    depends_on:
      - watchy-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./clocks/static:/static
    networks:
      - watchy_network

networks:
  watchy_network:
