services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    image: ghcr.io/phoniktop/clocks-backend:latest
    env_file:
      - .env
    depends_on:
      - watchy-redis
      - watchy-db
    volumes:
      - backend-static:/app/static
      - ./backend/secret_key:/app/secret_key
    environment:
      - REDIS_PASSWORD=passwo4509b14a24a8rd
    restart: always
    networks:
      - watchy_network

  watchy-redis:
    image: redis:latest
    container_name: watchy-redis
    restart: always
    command: >
      sh -c "exec redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./redis.prod.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=passwo4509b14a24a8rd
    networks:
      - watchy_network

  watchy-db:
    image: postgres:latest
    container_name: watchy-db
    env_file:
      - .env
    restart: always
    networks:
      - watchy_network

  watchy-frontend:
    container_name: watchy-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - backend-static:/static
    ports:
      - "82:80"
    networks:
      - watchy_network

networks:
  watchy_network:

volumes:
  redis-data:
  backend-static:
