version: '3.8'

services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    build:
      context: .
      dockerfile: Dockerfile
      target: watchy-api-local
    env_file:
      - ./docker.env
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
    depends_on:
      - watchy_redis
    volumes:
      - static:/Clocks/static

  watchy_redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  nginx:
    image: nginx:latest
    container_name: watchy-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - watchy-api
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static

volumes:
  redis_data:
  redis.conf:
  static:
