version: '3.8'

services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - clocks.env
    command: "uvicorn settings.asgi:application --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - watchy-redis
      - watchy-db
    volumes:
      - ./clocks/static:/Clocks/static
    restart: always
    networks:
      - watchy_network

  watchy-redis:
    image: redis:latest
    container_name: watchy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=password
    networks:
      - watchy_network

  watchy-db:
    image: postgres:14-alpine
    container_name: watchy-db
    ports:
      - "5432:5432"
    env_file:
      - clocks.env
    restart: always
    networks:
      - watchy_network

  watchy-nginx:
    image: nginx:latest
    container_name: watchy-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - watchy-api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./clocks/static:/Clocks/static
    networks:
      - watchy_network

networks:
  watchy_network:
