[tool.ruff]
extend-exclude = ["alembic", "migrations", "settings"]
respect-gitignore = true
per-file-ignores = { "__init__.py" = ["F403", "F405"], "**/tests/*.py" = ["S101", "ARG"] }

[tool.ruff.lint.isort]
split-on-trailing-comma = true
combine-as-imports = true
force-wrap-aliases = true

[tool.ruff.lint]
ignore = ["B008", "B904", "B009", "E501", "PTH118"]
# On top of the defaults (`E4`, E7`, `E9`, and `F`), enable flake8-bugbear (`B`) and flake8-quotes (`Q`).
# Details: https://docs.astral.sh/ruff/rules/
# C90 - comples struct
# C4 - comprehensions
# DTZ - timezone
# G - logging
# T20 - print
# PT - pytest
# Q - quotes
# SIM - simplify
# ARG - unused arg | On in future
# PTH - pathlib Instead of os.path
# PL - pylint
extend-select = ["B", "E", "W", "I", "S", "ASYNC", "C90", "C4",
    "DTZ", "G", "T20", "PT", "Q", "SIM", "PTH"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]


[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.pydocstyle]
convention = "google"