version: '3.8'

services:
  watchy-api:
    container_name: watchy-api
    hostname: watchy
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - clocks.env
    entrypoint: /scripts/api_entrypoint.sh
    command: "uvicorn settings.asgi:application --host 0.0.0.0 --port 8000"
    depends_on:
      - watchy_redis
      - watchy_db
    volumes:
      - static:/Clocks/static
    restart: always
    networks:
      - watchy_network

  watchy_redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=password
    networks:
      - watchy_network

  watchy_db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - clocks.env
    restart: always
    networks:
      - watchy_network

  nginx:
    image: nginx:latest
    container_name: watchy-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - watchy-api
    volumes:
      - ../../config/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - watchy_network

volumes:
  redis_data:
  static:

networks:
  watchy_network:
