# Generated by Django 5.1 on 2024-09-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='rooms.room'
            ),
        ),
    ]
