# Generated by Django 5.1 on 2024-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="status",
        ),
        migrations.AddField(
            model_name="session",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="votes",
            field=models.JSONField(default=None),
        ),
    ]
