# Generated by Django 5.1 on 2024-08-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_alter_session_votes"),
        ("rooms", "0002_room_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="room",
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("votes", models.JSONField(default=dict)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
