# Generated by Django 5.1 on 2024-08-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_remove_session_room_meeting"),
        ("rooms", "0003_remove_room_current_session_room_current_meeting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
