# Generated by Django 5.1 on 2024-09-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='room',
            new_name='room_id',
        ),
    ]
