# Generated by Django 5.1 on 2024-08-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="users",
            field=models.JSONField(default=list),
        ),
    ]
