# Generated by Django 5.1 on 2024-08-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_remove_session_room_meeting"),
        ("rooms", "0002_room_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="current_session",
        ),
        migrations.AddField(
            model_name="room",
            name="current_meeting",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_room",
                to="meetings.meeting",
            ),
        ),
    ]
